### ISSUE TITLE
Error when importing to project

### ISSUE THREAD

**Issue by norenma** [akserg/ng2-dnd#107]
* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **What is the current behavior?**

When I include DndModule.forRoot() in my module it fails, when I comment it out it runs.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via https://plnkr.co or similar.

* **What is the expected behavior?**

The module to run when DndModule.forRoot() is imported. 

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.1.0
- Browser: Chrome

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Error message in Chrome:

reflection_capabilities.js:58Uncaught TypeError: ctorParameters.map is not a function
    at ReflectionCapabilities.parameters (http://localhost:4200/main.bundle.js:45562:45)
    at Reflector.parameters (http://localhost:4200/main.bundle.js:45696:44)
    at CompileMetadataResolver.getDependenciesMetadata (http://localhost:4200/main.bundle.js:26089:54)
    at CompileMetadataResolver.getTypeMetadata (http://localhost:4200/main.bundle.js:26054:26)
    at CompileMetadataResolver.getDirectiveMetadata (http://localhost:4200/main.bundle.js:25829:28)
    at http://localhost:4200/main.bundle.js:25898:49
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/main.bundle.js:25891:44)
    at http://localhost:4200/main.bundle.js:25879:50
    at Array.forEach (native)
ReflectionCapabilities.parameters @ reflection_capabilities.js:58
Reflector.parameters @ reflector.js:27
CompileMetadataResolver.getDependenciesMetadata @ metadata_resolver.js:435
CompileMetadataResolver.getTypeMetadata @ metadata_resolver.js:400
CompileMetadataResolver.getDirectiveMetadata @ metadata_resolver.js:175
(anonymous) @ metadata_resolver.js:244
CompileMetadataResolver.getNgModuleMetadata @ metadata_resolver.js:237
(anonymous) @ metadata_resolver.js:225
CompileMetadataResolver.getNgModuleMetadata @ metadata_resolver.js:212
RuntimeCompiler._compileComponents @ runtime_compiler.js:133
RuntimeCompiler._compileModuleAndComponents @ runtime_compiler.js:71
RuntimeCompiler.compileModuleAsync @ runtime_compiler.js:62
PlatformRef_._bootstrapModuleWithZone @ application_ref.js:302
PlatformRef_.bootstrapModule @ application_ref.js:284
(anonymous) @ main.ts:12
__webpack_require__ @ bootstrap c4aed47…:52
(anonymous) @ .*$:7
__webpack_require__ @ bootstrap c4aed47…:52
webpackJsonpCallback @ bootstrap c4aed47…:23
(anonymous) @ main.bundle.js:1

**Comment by phixMe** [comment]
I am running into this exact same issue, does anybody have a resolution for this?

**Comment by norenma** [comment]
I solved it by updating to angular 2.4. Not sure if there is another way..

**Comment by NicoDino** [comment]
Just came across the same issue while running an angular 2.1 app.

Is there a way around this problem without updating?

Cheers

**Comment by akserg** [comment]
Hi all,
You can find the answer to your question [here](http://stackoverflow.com/questions/41285889/ctorparameters-map-is-not-a-function-in-angular2-mdl).
So, you have two options here:
- Migrate to Angular 2.4
- Fork the project and build it under Angular 2.1
