### ISSUE TITLE
Cannot read property 'length' of undefined on ng serve

### ISSUE THREAD

**Issue by ChrisTarasovs** [akserg/ng2-dnd#125]
* **I'm submitting a ...**
[x ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**
Does not compile

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via https://plnkr.co or similar.

1. ng new project X
2. install node_modules
3. Cloning the repo into src/app
4. Running node install 
5. Running ng build
6. ng serve

* **What is the expected behavior?**
to compile

* **Please tell us about your environment:**
Chriss-iMac:dragNdrop-ng2.4.9 christarasovs$ ng serve
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at createSourceFile (/Users/christarasovs/Desktop/dnd/dragNdrop-ng2.4.9/node_modules/typescript/lib/typescript.js:8980:109)
    at parseSourceFileWorker (/Users/christarasovs/Desktop/dnd/dragNdrop-ng2.4.9/node_modules/typescript/lib/typescript.js:8940:26)
    at Object.parseSourceFile (/Users/christarasovs/Desktop/dnd/dragNdrop-ng2.4.9/node_modules/typescript/lib/typescript.js:8899:26)
    at Object.createSourceFile (/Users/christarasovs/Desktop/dnd/dragNdrop-ng2.4.9/node_modules/typescript/lib/typescript.js:8727:29)
    at WebpackCompilerHost.getSourceFile (/Users/christarasovs/Desktop/dnd/dragNdrop-ng2.4.9/node_modules/@ngtools/webpack/src/compiler_host.js:210:27)
    at findSourceFile (/Users/christarasovs/Desktop/dnd/dragNdrop-ng2.4.9/node_modules/typescript/lib/typescript.js:45859:29)
    at processSourceFile (/Users/christarasovs/Desktop/dnd/dragNdrop-ng2.4.9/node_modules/typescript/lib/typescript.js:45790:27)
    at /Users/christarasovs/Desktop/dnd/dragNdrop-ng2.4.9/node_modules/typescript/lib/typescript.js:45901:17
    at Object.forEach (/Users/christarasovs/Desktop/dnd/dragNdrop-ng2.4.9/node_modules/typescript/lib/typescript.js:1115:30)
    at processReferencedFiles (/Users/christarasovs/Desktop/dnd/dragNdrop-ng2.4.9/node_modules/typescript/lib/typescript.js:45899:16)
    at findSourceFile (/Users/christarasovs/Desktop/dnd/dragNdrop-ng2.4.9/node_modules/typescript/lib/typescript.js:45884:21)
    at processSourceFile (/Users/christarasovs/Desktop/dnd/dragNdrop-ng2.4.9/node_modules/typescript/lib/typescript.js:45790:27)
    at processRootFile (/Users/christarasovs/Desktop/dnd/dragNdrop-ng2.4.9/node_modules/typescript/lib/typescript.js:45694:13)
    at /Users/christarasovs/Desktop/dnd/dragNdrop-ng2.4.9/node_modules/typescript/lib/typescript.js:45151:60
    at Object.forEach (/Users/christarasovs/Desktop/dnd/dragNdrop-ng2.4.9/node_modules/typescript/lib/typescript.js:1115:30)
    at Object.createProgram (/Users/christarasovs/Desktop/dnd/dragNdrop-ng2.4.9/node_modules/typescript/lib/typescript.js:45151:16)
    at AotPlugin._setupOptions (/Users/christarasovs/Desktop/dnd/dragNdrop-ng2.4.9/node_modules/@ngtools/webpack/src/plugin.js:124:28)
    at new AotPlugin (/Users/christarasovs/Desktop/dnd/dragNdrop-ng2.4.9/node_modules/@ngtools/webpack/src/plugin.js:23:14)
    at _createAotPlugin (/Users/christarasovs/Desktop/dnd/dragNdrop-ng2.4.9/node_modules/@angular/cli/models/webpack-configs/typescript.js:55:12)
    at Object.exports.getNonAotConfig (/Users/christarasovs/Desktop/dnd/dragNdrop-ng2.4.9/node_modules/@angular/cli/models/webpack-configs/typescript.js:70:19)
    at NgCliWebpackConfig.buildConfig (/Users/christarasovs/Desktop/dnd/dragNdrop-ng2.4.9/node_modules/@angular/cli/models/webpack-config.js:27:37)
    at Class.run (/Users/christarasovs/Desktop/dnd/dragNdrop-ng2.4.9/node_modules/@angular/cli/tasks/serve.js:37:98)
    at check_port_1.checkPort.then.port (/Users/christarasovs/Desktop/dnd/dragNdrop-ng2.4.9/node_modules/@angular/cli/commands/serve.js:103:26)
    at process._tickCallback (internal/process/next_tick.js:109:7)

- Angular version: 2.4.4
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by arlindonatal** [comment]
@ChrisTarasovs  I have same problem. Do you solved it?

**Comment by ChrisTarasovs** [comment]
@arlindonatal  the plugin is not built properly. Still struggling mate ;(
