### ISSUE TITLE
Critical error: ng2-dnd/ng2-dnd.d.ts, found version 4, expected 3, after Angular cli update

### ISSUE THREAD

**Issue by BartMommens** [akserg/ng2-dnd#230]
* **I'm submitting a ...**
[*] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

Failes to run / compile after ANGULAR CLI UPDATE

ERROR in Error: Metadata version mismatch for module node_modules/ng2-dnd/ng2-dnd.d.ts, found version 4, expected 3, resolving symbol AppModule in src/app/app.module.ts, resolving symbol AppModule in src/app/app.module.ts, resolving symbol AppModule in /src/app/app.module.ts
    at Error (native)
    at syntaxError (node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at simplifyInContext (node_modules/@angular/compiler/bundles/compiler.umd.js:24979:23)
    at StaticReflector.simplify node_modules/@angular/compiler/bundles/compiler.umd.js:24991:13)
    at StaticReflector.annotations (node_modules/@angular/compiler/bundles/compiler.umd.js:24418:41)
    at _getNgModuleMetadata (node_modules/@angular/compiler-cli/src/ngtools_impl.js:138:31)
    at _extractLazyRoutesFromStaticModule (/node_modules/@angular/compiler-cli/src/ngtools_impl.js:109:26)
    at Object.listLazyRoutesOfModule (node_modules/@angular/compiler-cli/src/ngtools_impl.js:53:22)
    at Function.NgTools_InternalApi_NG_2.listLazyRoutes (node_modules/@angular/compiler-cli/src/ngtools_api.js:91:39)
    at AotPlugin._getLazyRoutesFromNgtools (node_modules/@ngtools/webpack/src/plugin.js:212:44)
    at _donePromise.Promise.resolve.then.then.then.then.then (node_modules/@ngtools/webpack/src/plugin.js:448:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via https://plnkr.co or similar.

Project worked, until update Angular cli

* **What is the expected behavior?**

***

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
ANGULAR CLI
@angular/cli: 1.4.9
node: 6.10.3
os: darwin x64
*angular/common: 4.4.6
*angular/compiler: 4.4.6
*angular/core: 4.4.6
*angular/forms: 4.4.6
*angular/http: 4.4.6
*angular/platform-browser: 4.4.6
*angular/platform-browser-dynamic: 4.4.6
*angular/router: 4.4.6
*angular/cli: 1.4.9
*angular/compiler-cli: 4.4.6
typescript: 2.2.2

- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Thank you for taking your time looking into this issue!

Best regards,
Bart

**Comment by BartMommens** [comment]
Updating to Angular 5 solved this issue, might i suggest to leave this issue in closed so people face this issue might find this solution? 

Thank you for this plugin and maintaining it 

Best regards,
Bart

**Comment by akserg** [comment]
Hi Bart,

Sure.

**Comment by tirlipinpon** [comment]
Hello when V4.2.0 had some issue with angular 4 (drag-drop not properly works, or data undefined)
I upgraded from V4.2.0 to 5.0.0 for my angular v 5
But still ERROR in Metadata version mismatch for module ng2-dnd.d.ts found version 4, expected 3.
Some idee ?
