### ISSUE TITLE
Cannot set a custom dragImage=""

### ISSUE THREAD

**Issue by silentHoo** [akserg/ng2-dnd#63]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**
*bug*

* **What is the current behavior?**
It's not possible to set a custom drag image like it's described in **any of the three possibilities** here: https://github.com/akserg/ng2-dnd/blob/master/src/draggable.component.ts#L54

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via https://plnkr.co or similar.

Just use the code provided here: https://github.com/akserg/ng2-dnd/blob/master/src/draggable.component.ts#L54

* **What is the expected behavior?**

The image provided via `String`, `DragImage` or a function which returns a path to any image should be enough to have an image attached beside the mouse cursor.

* **What is the motivation / use case for changing the behavior?**

-

* **Please tell us about your environment:**

- ng2-dnd v1.12.0
- Angular version: 2.0.0-rc.4
- Browser: Chrome 52

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

````
browser_adapter.ts:82 TypeError: Illegal constructor
    at TypeError (native)
    at Object.createImage (http://localhost:4200/vendor/ng2-dnd/src/dnd.utils.js:27:15)
    at HTMLLIElement.AbstractComponent._elem.ondragstart (http://localhost:4200/vendor/ng2-dnd/src/dnd.component.js:70:69)
    at HTMLLIElement.wrapFn [as _ondragstart] (http://localhost:4200/vendor/zone.js/dist/zone.js:794:30)
    at ZoneDelegate.invokeTask (http://localhost:4200/vendor/zone.js/dist/zone.js:365:38)
    at Object.onInvokeTask (http://localhost:4200/vendor/@angular/core/src/zone/ng_zone_impl.js:44:41)
    at ZoneDelegate.invokeTask (http://localhost:4200/vendor/zone.js/dist/zone.js:364:43)
    at Zone.runTask (http://localhost:4200/vendor/zone.js/dist/zone.js:265:48)
    at HTMLLIElement.ZoneTask.invoke (http://localhost:4200/vendor/zone.js/dist/zone.js:433:34)
````

**Comment by rmcsharry** [comment]
Confirmed, I am seeing the same error with the latest version of the library with Angular 2.3.

If you pass a function which returns a string you also get this error. But if you hard code the string in the html you get a cannot parse .jpg error.
