### ISSUE TITLE
issue when run de_modules/.bin/ng-xi18n

### ISSUE THREAD

**Issue by githubfengyun** [akserg/ng2-dnd#73]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**
issue happend when run ./node_modules/.bin/ng-xi18n
Error: Unexpected value 'DND_DIRECTIVES' exported by the module 'SharedModule'
at /Users/jackysun/Desktop/MLab/portal/node_modules/@angular/compiler/bundles/compiler.umd.js:14153:33
at Array.forEach (native)
at CompileMetadataResolver.getNgModuleMetadata (/Users/jackysun/Desktop/MLab/portal/node_modules/@angular/compiler/bundles/compiler.umd.js:14136:46)
at /Users/jackysun/Desktop/MLab/portal/node_modules/@angular/compiler/bundles/compiler.umd.js:12952:58

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via https://plnkr.co or similar.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
mac system

- Angular version: 2.0.0
 "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "2.0.0",
    "@angular/compiler-cli": "^0.6.4",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/platform-server": "^2.0.2",
    "@angular/router": "3.0.0",
    "@ng-bootstrap/ng-bootstrap": "1.0.0-alpha.7",
    "angular2-localstorage": "^0.4.0",
    "bootstrap": "^4.0.0-alpha.4",
    "core-js": "^2.4.1",
    "ng2-dnd": "^2.0.1",
    "rxjs": "5.0.0-beta.12",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.23"
  },
  "devDependencies": {
    "@types/jasmine": "^2.2.30",
    "angular-cli": "1.0.0-beta.14",
    "codelyzer": "~0.0.26",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.5",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "2.0.2"
  }
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by akserg** [comment]
Please use latest 2.2.1 version
