### ISSUE TITLE
Drag-and-Drop doesn't work on IE 11

### ISSUE THREAD

**Issue by akserg** [akserg/ng2-dnd#8]
When starts dragging the browser prompts with following exception:

```
EXCEPTION: Error: Unexpected call to method or property access.
   EXCEPTION: Error: Unexpected call to method or property access.
   STACKTRACE:
   Error: Unexpected call to method or property access.
   at _elem.ondragstart (http://akserg.github.io/ng2-webpack-demo/boot.1fc11a8a003f8c49b196.bundle.js:504:18)
   at Zone.prototype.run (http://akserg.github.io/ng2-webpack-demo/polyfills.f737c0c46c4580435f22.bundle.js:8959:15)
   at Anonymous function (http://akserg.github.io/ng2-webpack-demo/vendor.758044ce30c8786a3ac1.bundle.js:12567:26)
   at zoneBoundFn (http://akserg.github.io/ng2-webpack-demo/polyfills.f737c0c46c4580435f22.bundle.js:8936:15)

SCRIPT65535: Unexpected call to method or property access.
File: vendor.758044ce30c8786a3ac1.bundle.js, Line: 18850, Column: 14
```

**Comment by akserg** [comment]
The `dataTransfer.setData` works only with `text` type, so I changed my code form :
```javascript
e.dataTransfer.setData("text/html", g.destination);
```
to 
```javascript
e.dataTransfer.setData("text", g.destination);
```

**Comment by ronbnsim** [comment]
++
